# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - "*"

stages:
- stage: Build

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-bullseye
      artifact_name: sonic-linux-kernel

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: arm64
      pool: sonicbld-arm64
      sonic_slave: sonic-slave-bullseye-arm64
      artifact_name: sonic-linux-kernel.arm64

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: armhf
      pool: sonicbld-armhf
      sonic_slave: sonic-slave-bullseye-armhf
      artifact_name: sonic-linux-kernel.armhf

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: arm64
      platform: pensando
      pool: sonicbld-arm64
      sonic_slave: sonic-slave-bullseye-arm64
      artifact_name: sonic-linux-kernel.pensando.arm64

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      platform: mellanox
      sonic_slave: sonic-slave-bullseye
      artifact_name: sonic-linux-kernel.mellanox.amd64

